
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spiltwise
    username: root
    password: Rahul@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 248537161707-ueuj3pscgkilmqrvbmmbjld4bsvc27to.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 121189305185277
            clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            clientId: d3e47fc2ddd966fa4352
            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

app:
  zoneId: Asia/Kolkata
  auth:
    jwtCookieName: bezkoder
    jwtRefreshCookieName: bezkoder-jwt-refresh
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 8640000
    jwtRefreshExpirationMs: 86400000
  cors:
    allowCredentials: true
    allowedOrigins:
      - http://localhost:3000
      - http://54.253.132.48:3000
      - http://192.168.29.228:3000
      - http://newfeedrecatclone.s3-website-us-east-1.amazonaws.com
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
    allowedHeaders:
      - "*"
